production:
  MERCHANT_KEY_ID:  'rzp_test_aFsD9MxwfYu8Zb'
  MERCHANT_KEY_SECRET:  'Dj94J7gRWP73mCs6huHQjbxo'

development:
  MERCHANT_KEY_ID:  'rzp_test_aFsD9MxwfYu8Zb'
  MERCHANT_KEY_SECRET:  'Dj94J7gRWP73mCs6huHQjbxo'